config/routes.rb
Rails.application.routes.draw do
  root 'index#home'

  get 'users/index'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/drop/:question_id', to: 'users#drop'

  get '/questions', to: 'questions#index'
  get '/scores', to: 'scores#index'

  get '/created_question', to: 'users#created_question'

  get 'index/show'
  get '/challenge', to: 'index#question'
  get '/answer', to: 'index#answer'

  resources :questions
  resources :tags
  resources :scores
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like_unlike_question.rb
class LikeUnlikeQuestion < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :question_tags
  has_many :tags, through: :question_tags
  has_many :like_unlike_questions
  has_many :likeOrUnlike, through: :like_unlike_questions
end

app/models/question_tag.rb
class QuestionTag < ApplicationRecord
  belongs_to :question
  belongs_to :tag
end

app/models/score.rb
class Score < ApplicationRecord
  has_one :users
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :question_tags
  has_many :questions, through: :question_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :scores, optional: true
  has_many :questions
  has_many :like_unlike_questions
  has_many :likeOrUnlike, through: :like_unlike_questions

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :require_login
  include ApplicationHelper
  def require_login
    if !logged_in?
      redirect_to login_path
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
    @questions = Question.all
    @scores = Score.all
  end

  def question
    @question = Question.all.sample()
    @score = User.find(current_user.id).score
  end

  def answer
    user = User.find(current_user.id)
    question_id = params[:question_id]
    answer = params[:answer]
    question = Question.find(question_id)

    @question = question
    @result = false
    if @question.answer == answer
      @result = true
      user.increment!(:score, by=4)
    else
      user.increment!(:score, by=-1)
    end
    @score = user.score
  end

  def show
    @questions = Question.first
    respond_to do |format|
      format.js { render layout: false } # Add this line to you respond_to block
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Qeustion was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:description, :option1, :option2, :option3, :option4, :answer)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  # GET /scores
  # GET /scores.json
  def index
    @scores = User.order("score DESC")
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to created_question_path
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
      log_in @user
      flash[:success] = 'Welcome to Question Answer Game'
      redirect_to @user
    else
      render 'new'
    end
  end

  def drop
    Question.where(user_id: current_user.id).first.destroy
    flash[:success] = 'Question successfully deleted!'

    redirect_to created_question_path
  end

  def created_question
    @user = current_user
    @questions = current_user.questions.all
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/answer.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Question: <%= @question.description %></h5>
    <p>Your answer: <%= @result %></p>
    <p>Correct answer: <%= @question.answer %> </p>

    <p>Total score: <%= @score %></p>

    <%= link_to "Next question", challenge_path, class: "btn btn-primary card-link" %>
  </div>
</div>

app/views/index/home.html.erb
<h1 class="text-center my-5">Welcome to Question Answer Game</h1>

<%= link_to "Start Challenge", challenge_path, class: "btn btn-primary" %>


<% %>
<!--<ul class="nav nav-tabs" id="myTab" role="tablist">-->
<!--  <li class="nav-item">-->
<!--    <a class="nav-link active" id="question-tab" data-toggle="tab" href="#question" role="tab" aria-controls="question" aria-selected="true">Question</a>-->
<!--  </li>-->
<!--  <li class="nav-item">-->
<!--    <a class="nav-link" id="score-tab" data-toggle="tab" href="#score" role="tab" aria-controls="score" aria-selected="false">Scoreboard</a>-->
<!--  </li>-->
<!--</ul>-->

<!--<div class="tab-content" id="myTabContent">-->
  <%# Question tab %>
<!--  <div class="tab-pane show active" id="question" role="tabpanel" aria-labelledby="question-tab">-->
<!--    <table class="table table-responsive table-striped">-->
<!--      <thead>-->
<!--      <tr>-->
<!--        <th>Tag</th>-->
<!--        <th>Description</th>-->
<!--      </tr>-->
<!--      </thead>-->

<!--      <tbody>-->
      <%# @questions.each do |question| %>
<!--        <tr>-->
<!--          <td><%#= question.tag %></td>-->
<!--          <td><%#= question.description %></td>-->
<!--        </tr>-->
      <%# end %>
<!--      </tbody>-->
<!--    </table>-->
<!--  </div>-->

  <%# Scoreboard tab %>
<!--  <div class="tab-pane fade" id="score" role="tabpanel" aria-labelledby="score-tab">-->
<!--    <table class="table table-responsive table-striped">-->
<!--      <thead>-->
<!--      <tr>-->
<!--        <th>Name</th>-->
<!--        <th>Score</th>-->
<!--      </tr>-->
<!--      </thead>-->

<!--      <tbody>-->
      <%# @scores.each do |score| %>
<!--        <tr>-->
<!--          <td><%#= score.name %></td>-->
<!--          <td><%#= score.value %></td>-->
<!--        </tr>-->
      <%# end %>
<!--      </tbody>-->
<!--    </table>-->
<!--  </div>-->
<!--</div>-->

app/views/index/question.html.erb
<h4 class="my-3">Your score: <%= @score %> </h4>


<% if @question %>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @question.description %></h5>

      <%= form_with(url: answer_path, method: :get, local: true) do |form| %>

        <div class="form-check">
          <%= form.radio_button :answer, @question.option1, checked: true, class: 'form-check-input' %>
          <%= label :option1, @question.option1 %>
        </div>

        <div class="form-check">
          <%= form.radio_button :answer, @question.option2, class: 'form-check-input' %>
          <%= label :option1, @question.option2 %>
        </div>

        <div class="form-check">
          <%= form.radio_button :answer, @question.option3, class: 'form-check-input' %>
          <%= label :option1, @question.option3 %>
        </div>

        <div class="form-check">
          <%= form.radio_button :answer, @question.option4, class: 'form-check-input' %>
          <%= label :option1, @question.option4 %>
        </div>

        <%= form.hidden_field :question_id, value: @question.id %>
        <%= form.submit "Submit", class: 'btn btn-primary card-link' %>
        <%#= link_to "Next question", challenge_path, class: "btn btn-primary card-link" %>
      <% end %>

    </div>
  </div>


<% else %>
  <h3>No questions yet. </h3>
  <%= link_to 'Create a new one?', new_question_path %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-5 mb-3">
  <small>The <%= link_to 'Question Answer Game', 'https://github.com/zwang759/question-answer-game' %> </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="nav navbar navbar-expand-lg navbar-dark" style="background-color: #212121;">
  <%= link_to "Question Answer Game", root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Question", questions_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Score", scores_path, class: "nav-link" %>
      </li>

      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Me</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <p class="dropdown-item">Hi, <%= current_user.name %></p>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <%= link_to "Log in", login_path, class: "nav-link"%>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionAnswerGame</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/header' %>

<div class="container mx-auto">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :Option1 %>
    <%= form.text_field :option1 %>
  </div>

  <div class="field">
    <%= form.label :Option2 %>
    <%= form.text_field :option2 %>
  </div>

  <div class="field">
    <%= form.label :Option3 %>
    <%= form.text_field :option3 %>
  </div>

  <div class="field">
    <%= form.label :Option4 %>
    <%= form.text_field :option4 %>
  </div>

  <div class="field">
    <%= form.label :Answer %>
    <%= form.text_field :answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', 'javascript:history.back()' %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center my-5">Questions</h1>

<table class="table table-responsive table-striped">
  <thead>
  <tr>
    <th>Description</th>
    <th>Option 1</th>
    <th>Option 2</th>
    <th>Option 3</th>
    <th>Option 4</th>
    <th>Answer</th>
    <th colspan="6"></th>
  </tr>
  </thead>

  <tbody>
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.description %></td>
      <td><%= question.option1 %></td>
      <td><%= question.option2 %></td>
      <td><%= question.option3 %></td>
      <td><%= question.option4 %></td>
      <td><%= question.answer %></td>
      <td><%= link_to 'Show', question %></td>
      <td><%= link_to 'Edit', edit_question_path(question) %></td>
      <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', 'javascript:history.back()' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>

<p>
  <strong>Option 1:</strong>
  <%= @question.option1 %>
</p>

<p>
  <strong>Option 2:</strong>
  <%= @question.option2 %>
</p>

<p>
  <strong>Option 3:</strong>
  <%= @question.option3 %>
</p>

<p>
  <strong>Option 4:</strong>
  <%= @question.option4 %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', 'javascript:history.back()' %>

app/views/questions/start.html.erb
<%= form_tag assessment_answers_path(method: :post), :name => 'example-1', :id => 'wrapped' do %>

  <% @empty_answers.each do |answer| %>

    <%= fields_for 'answers[]', answer, include_id: false do |r| %>

      <% q = AssessmentQuestion.where(order: @empty_answers.index(answer) + 1).first %>

      <%= r.collection_radio_buttons(:letter, q.assessment_options.order(“letter”), :letter, :answer, include_hidden: false) do |r| %>

        <div class=”form-group radio_input”>
          <%= r.radio_button(class: 'icheck', name: 'answers[' + (q.order — 1).to_s + '][letter]') + r.label(:class => '') %>
        </div>

      <% end %>


      <%= r.hidden_field :assessment_question_id, value: q.id, name: 'answers[' + @empty_answers.index(answer).to_s + '][assessment_question_id]' %>

      <%= r.hidden_field :assessment_id, value: params[:assessment_id], name: 'answers[' + @empty_answers.index(answer).to_s + '][assessment_id]' %>

    <% end %>

  <% end %>

  <div id=”bottom-wizard”>
    <button type=”button” name=”backward” class=”backward”>Backward</button>
    <button type=”button” name=”forward” class=”forward”>Forward</button>
    <button type=”submit” name=”process” class=”submit”>Submit</button>
  </div><! — /bottom-wizard →

<% end %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center my-5">Scoreboard</h1>

<table class="table table-responsive table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @scores.each do |record| %>
    <tr>
      <td><%= record.name %></td>
      <td><%= record.score %></td>
<!--      <td><%#= link_to 'Show', user %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/created_question.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center my-5">
  <%= @user.name %>
</h1>

<h3 class="my-3">Created Questions:</h3>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Description</th>
    <th>Option 1</th>
    <th>Option 2</th>
    <th>Option 3</th>
    <th>Option 4</th>
    <th>Answer</th>
    <th colspan="6"></th>
  </tr>
  </thead>

  <tbody>
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.description %></td>
      <td><%= question.option1 %></td>
      <td><%= question.option2 %></td>
      <td><%= question.option3 %></td>
      <td><%= question.option4 %></td>
      <td><%= question.answer %></td>
      <td><%= link_to 'Drop', "/drop/#{question.id}", class: 'btn btn-primary', method: :post %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="card shadow-lg mx-auto my-5">
  <div class="card-body">
    <h1 class="card-title text-center mt-3 mb-5">Sign up</h1>
    <div class="col mx-auto">
      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.text_field :name, class: 'form-control mb-3', placeholder: 'Name'%>

        <%= f.email_field :email, class: 'form-control mb-3', placeholder: 'E-mail'%>

        <%= f.password_field :password, class: 'form-control mb-3', placeholder: 'Password'%>

        <%= f.password_field :password_confirmation, class: 'form-control mb-4', placeholder: 'Password Confirmation'%>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1 class="text-center my-5">
  <%= @user.name %>
</h1>